version: '3.9'

services:
  rabbitmq:
    image: 'rabbitmq:3.12.4-management-alpine'
    container_name: 'payment-app-rabbitmq'
    # DEV Environment
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672