#### ONLY FOR POETRY FOR PY 
#### AND NPM FOR TYPESCRIPT

name: Code Quality Checks

on:
  push:
    branches:
      - develop
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  python-lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies (POETRY ONLY)
        run: |
          python -m poetry update --upgrade pip
          pip install pylint

      - name: Lint with pylint
        run: pylint "../backend/ ../libs/shared/DataPipelineService ../libs/shared/OpticNerveObservability"

  typescript-lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Lint with ESLint
        run: npx eslint "../frontend/**/*.ts ../backend/**/*.ts ../libs/shared/**/*.ts"

  check-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Datadog Static Analyzer
        uses: DataDog/datadog-static-analyzer-github-action@v1
        with:
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_service: "my-service"
          dd_env: "ci"
          cpu_count: 2
          enable_performance_statistics: false

